server:
  port: 9000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: route1
          uri: http://localhost:8080/
          predicates:
            - Path=/resource/**
        - id: angular
          uri: http://localhost:4200/
          predicates:
            - Path=/**
        - id: yt
          uri: https://www.youtube.com
          predicates:
            - Path=/yt
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: spring
            client-id: gateway
            client-secret: secret
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9000/login/oauth2/code/gateway
        provider:
          spring:
            issuer-uri: http://localhost:8100
