spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-producto
          uri: lb://service-producto
          predicates:
            - Path=/api/productos/**
            - Method=GET, POST
          filters:
            - StripPrefix=2
        - id: node-msc
          uri: lb://node-msc
          predicates:
            - Path=/api/clientes/**
            - Method=GET, POST
          filters:
            - StripPrefix=2