logging:
  level:
    org.springframework: DEBUG
    org.springframework.cloud.gateway: TRACE
spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-producto
          uri: http://localhost:8001
          predicates:
            - Path=/api/almacen/**
            - Method=GET, POST
          filters:
            - StripPrefix=2
server:
  port: 9000