spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-producto
          uri: http://localhost:8080
          predicates:
            - Path=/api/almacen/**
            - Method=GET, POST
          filters:
            - StripPrefix=2